### PR TITLE
Factory reset and soft reset.

### LINKED ISSUE #2: Reset flow
Allow user to rest credentials to wifi if they messed up (could be just enabling special mode in setting to switch back to AP mode)

### PR DESCRIPTION
**Pull request by carlhampuswall**
Factory reset to ota_0 partition.
Reset configuration and set OSMode to Onboarding.

Factory reset is ran after holding boot button (GPIO 0) for 10 seconds.

Closes #2

### CODE REVIEW

**Comment by carlhampuswall** [comment]
Do we want to reset to ota_0 (factory flashed image) or do we want to just reset config for now? And enable true factory reset later with a newer revision of the firmware?

**Review by brushknight — APPROVED** [review]

**Comment by carlhampuswall** [comment]
Soft reset is hold for 5s. Hard reset/factory is 6 quick presses.

**Review by brushknight — COMMENTED** [review]
I believe it is better to keep hold 5 - 15 seconds instead of hold and 6 quick presses

**Comment by carlhampuswall** [comment]
> I believe it is better to keep hold 5 - 15 seconds instead of hold and 6 quick presses

My opinion here was that its harder to do 6 quick presses accidentally than holding it down for 15 sec to prevent none intentional HARD resets.

@nicolabortignon any opinion?

**Comment by brushknight** [comment]
the problem is that buttons are in not the best location for 6 clicks onder 0.5s each

**Comment by carlhampuswall** [comment]
> the problem is that buttons are in not the best location for 6 clicks under 0.5s each

thats true, hmm

**Comment by carlhampuswall** [comment]
> the problem is that buttons are in not the best location for 6 clicks under 0.5s each

Will change back to 15s and create issue for adding UI for updates during reset.

**Comment by carlhampuswall** [comment]
@brushknight 
Will work on UI for reset tomorrow. Left some comments in the code for if we ever wanna use multiple presses for any action.

**Review by brushknight — APPROVED** [review]

**Pull request merged**
