### PR TITLE
Added flashing step for recovery firmware. Some small fixes.

### PR DESCRIPTION
**Pull request by carlhampuswall**

### CODE REVIEW

**Comment by carlhampuswall** [comment]
Closes #36

**Comment by nicolabortignon** [comment]
couldn't test this, but from a cursory read looks good

**Comment by carlhampuswall** [comment]
@nicolabortignon Needs ur testing as ur the one who mostly runs it and its not been tested on OSX.

**Comment by nicolabortignon** [comment]
tested and works

**Review by nicolabortignon — APPROVED** [review]

**Pull request merged**
